language: ruby
rvm:
- 2.6.2
before_install:
- gem update --system
- gem install bundler
- pyenv global 3.6.3
- pip install --upgrade pip
- pip install proselint
install:
- bundle install
- npm install -g htmlhint csslint
script:
- mdl README.md
- mdl _posts
- proselint README.md
- proselint _posts
- jekyll build
- htmlproofer ./_site
- htmlhint ./_site
- csslint ./_site
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
sudo: false
cache: bundler
notifications:
  email: false
deploy:
  provider: rubygems
  api_key: $RUBYGEMAPIKEY
  gem: jekylldark
  on:
    repo: sutterj/jekylldark
