# Site settings
title: jekylldark
title-description: A dark theme for jekyll.
full-description: >
  A dark theme for jekyll with responsive layout
  that features a navbar, sidebar, footer, content
  area, and posts with customizable text through
  YML files.
email: jesutter23@me.com
url: https://jekylldark.jacobsutter.com
google-analytics: UA-138245538-2

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Include in processing
include:
  - _redirects

# Exclude from processing
exclude:
  - /*.gem
  - /*.gemspec
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE
