title: jekylldark
description: >-
  A dark theme for jekyll.

exclude:
  - /*.gem
  - /*.gemspec
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE.txt
