# Site settings
title: jekylldark
title-description: A dark theme for jekyll.
full-description: >
  A dark theme for jekyll with responsive layout
  that features a navbar, sidebar, footer, content
  area, and posts with customizable text through
  YML files.

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing
exclude:
  - /*.gem
  - /*.gemspec
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE
